# Generated by Django 5.0.2 on 2024-02-11 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn_models", "0002_manufacturer_car"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="car",
            table="car",
        ),
        migrations.AlterModelTable(
            name="manufacturer",
            table="manufacturer",
        ),
    ]
