# Generated by Django 5.0.2 on 2024-02-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn_models", "0003_alter_car_table_alter_manufacturer_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learn_models.manufacturer",
            ),
        ),
    ]
