# Generated by Django 5.0.2 on 2024-02-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adverts.chat",
            ),
        ),
    ]
