# Generated by Django 5.0.2 on 2024-02-11 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0002_user_alter_advert_chat_alter_chat_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
